### ISSUE TITLE
Disassembles seemingly wrong `.asciz`?

### ISSUE THREAD

**Issue by Fuuzetsu** [Decompollaborate/spimdisasm#121]
I'm decompiling `Tenchu: Shinobi Gaisen` for the PS1. The main game binary `main.exe` has a section early on with some bytes as follows:

```
00 00 bc 02
a2 fe 00 00
```

I'm using [splat](https://github.com/ethteck/splat/) and specify the section as `rodata`: I apologies for no reproducer.

In the resulting disassembled file, I see the following:

```
glabel D_80011ae4
/* 12E4 80011AE4 0000BC02 */ .word 0x02BC0000

glabel D_80011ae8
/* 12E8 80011AE8 */ .asciz "◯"
                      .balign 4
```

After reassembling, I diff the original binary with my assembled binary and I see the following:

```diff
-000012e0: 24fa 0000 0000 bc02 a2fe 0000 0000 c201  $...............
+000012e0: 24fa 0000 0000 bc02 e297 af00 0000 c201  $...............
```

Some ASCII to binary online tool tells me that `◯` is `e2 97 af`. So it appears that `spimdisasm` has taken `a2 fe 00 00` and turned it into `.asciz "◯" .balign 4` which translates back to `e2 97 af 00` instea dof `a2 fe 00 00` as it was in the original.

---

I have other differing location in the same file and they all seem to correspond to `asciz`. There are more cases of `◯` but I see some others too. For example, there's a sequence of bytes:

```
d4fe 0000
```

and it gets turned into

```
glabel D_80011b28
/* 1328 80011B28 */ .asciz "奩"
                      .balign 4
```

which then gets reassembled correctly to

```
e5a5 a9000
```

One more case is

`e0fc 0000` -> `.asciz "瓏"` -> `e793 8f00`.

I'm not sure what's happening or even sure if `spimdisasm` is the right repository to file the ticket: but if I had to make an uneducated guess, I would guess:

* `spimdisasm` figures something looks like null-terminated ASCII(?) even though the actual string doesn't make much sense ASCII-wise (`奩` is not part of ASCII for sure)
* it gets put into the dumped out assembly as UTF-8: `.asciz 奩`
* when assebling this, `奩` gets interpretted as UTF-8 which is `e5a5 a9…`
* we end up with a difference

I suppose it should never emit anything outside of usual code range as `asciz`?

Please let me know if issue is not with `spimdisasm` but something else, or if I'm misconfiguring it (running via `splat`) or something.

**Comment by AngheloAlf** [comment]
By default spimdisasm assumes the string encoding used by a binary is `EUC-JP` and try its best to identify strings in rodata using that encoding by converting them `UTF-8`, meaning building those without modification will likely not match by default. What most projects do when they have non `ASCII` strings is to convert them with `iconv` and then pipe the output to a compiler.

Since `EUC-JP` shares the same initial values as `ASCII` this is usually not a problem if a binary only has `ASCII` strings, but if you know your game does use a different string encoding (`SHIFT-JIS`, `EUC-CN`, `ASCII`, etc) by specifying it in the splat's yaml options.

```yaml
  string_encoding: SHIFT-JIS
```

This accepts any encoding supported by your [python version](https://docs.python.org/3.11/library/codecs.html#standard-encodings)

**Comment by AngheloAlf** [comment]
> > which then gets reassembled correctly to
> 
> Well, I guess it's questionable that assembling `asciz` contents that aren't actually ASCII shouldn't just error out but I don't know if there's some standard or rationale for this...

`.asciz` is just an [assembler directive](https://sourceware.org/binutils/docs/as/Asciz.html#Asciz) used to have strings in assembly files. It just reads the contents inside the quotes and writes them as is (and appends a zero, hence the `z` in the name). I can understand how the name itself can be confusing, but it isn't meant to be used only with `ASCII` characters.

`.asciz` is preferred over [`.string`](https://sourceware.org/binutils/docs/as/String.html#String) because it is more widely supported in assemblers

**Comment by AngheloAlf** [comment]
I have to agree spimdisasm's documentation is almost non-existent and that's my fault. Sorry.

I'll close this since it seems to be solved. Feel free to reopen/open a new issue if more problems arise.
