### ISSUE TITLE
help file

### ISSUE THREAD

**Issue by mediotex** [Decompollaborate/spimdisasm#166]
I installed spimdisasm, but have some problem: its unclear how to setup the correct command format to disassemle raw MIPS machine code. (image.out)
```
~/.local/bin$ python3 spimdisasm singleFileDisasm --arch-level MIPS32 --endian little binary image1.out >result
Warning: globalSegment's will has its vromStart equal to the vromEnd (0x0)
Traceback (most recent call last):
  File "/home/testkon/.local/bin/spimdisasm", line 8, in <module>
    sys.exit(cliMain())
  File "/home/testkon/.local/lib/python3.9/site-packages/spimdisasm/frontendCommon/FrontendUtilities.py", line 273, in cliMain
    return int(args.func(args))
  File "/home/testkon/.local/lib/python3.9/site-packages/spimdisasm/singleFileDisasm/SingleFileDisasmInternals.py", line 186, in processArguments
    fec.FrontendUtilities.writeProcessedFiles(processedFiles, processedFilesOutputPaths, processedFilesCount, progressCallback)
  File "/home/testkon/.local/lib/python3.9/site-packages/spimdisasm/frontendCommon/FrontendUtilities.py", line 152, in writeProcessedFiles
    mips.FilesHandlers.writeSection(filePath, f)
  File "/home/testkon/.local/lib/python3.9/site-packages/spimdisasm/mips/FilesHandlers.py", line 63, in writeSection
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: 'image1.out'
```

[image.out.zip](https://github.com/user-attachments/files/16042240/image.out.zip)

**Comment by AngheloAlf** [comment]
It is complaining because you passed the arguments on the wrong order, it is interpreting `binary` as the input file and `image1.out` as the desired output directory.
Also, the zip file you posted contains a `image.out` file, not a `image1.out`.

Btw, are you sure this file contains MIPS instructions? it doesn't seem to be the case, at least not at the beginning of the file. If the executable part of the binary is not at the beginning of the file you may want to use the `--start` and `--end` parameters to specify the offset within the file, you'll probably want to pass the `--vram` parameter too.

**Comment by mediotex** [comment]
On my first try I just followed help file on positional arguments:
```
 binary                Path to input binary
 output                Path to output. Use '-' to print to stdout instead
```
I was wrong here, I realized it then. 
image1.out is the same file with image.out. I just tried on another laptop. I got [results](https://drive.google.com/file/d/1uq11__WZtBkl6gexO5geHmhRDSisL2li/view?usp=sharing), but its contains a plenty of invalid instructions and not suitable for further use.
Yes, its raw MIPS machine code and its loaded at RAM address 0x80004000
Here is output of `binwalk` against the file:
```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
496           0x1F0           eCos kernel exception handler, architecture: MIPS, exception vector table base address: 0x80000300
25148         0x623C          Certificate in DER format (x509 v3), header length: 4, sequence length: 32
103948        0x1960C         Certificate in DER format (x509 v3), header length: 4, sequence length: 128
4340413       0x423ABD        bix header, header size: 64 bytes, header CRC: 0x431025AE, created: 1988-01-29 04:05:34, image size: 50335744 bytes, Data Address: 0x31A0030, Entry Point: 0x63FF008E, data CRC: 0x24000C3C, OS: NetBSD, image name: "B"
```
Also, there are 3 references in binwalk to big endian
`9496624       0x90E830        CRC32 polynomial table, big endian`
So, its probably a `Big endian` architecture, not Little endian? I have specified in command a `little endian`.

Can you show a full command to disassemble this file?

**Comment by AngheloAlf** [comment]
As I mentioned on my earlier comment, you probably need to pass a `--start` and `--end` to specify the offsets within the binary file.
Assuming the output you posted is correct then you could try disassembling that first chunk of code by passing `--start 0x1F0 --end 0x623C --vram 0x80000300`, so something like this
```bash
$ python3 -m spimdisasm singleFileDisasm image.out out_dir --start 0x1F0 --end 0x623C --vram 0x80000300
```
(spimdisasm assumes big endian by default)

If you get any chunk of stuff that does not get disassembled but you know it should be valid code then you could slap `--disasm-unknown` and see what it produces.

**Comment by mediotex** [comment]
Now is much better, a lot of /* invalid instruction */ marks still in output. But I'm not sure does it should be valid code or not.
I run 2nd test with `--disasm-unknown` argument,  both output [attached](https://drive.google.com/file/d/1jFG2vcGFpPAX0uMkqsUZcc4I5Qrt0IVp/view?usp=sharing). Is it possible to define what is correct `endian` type for that binary? And how it can affect on disassembling result?

**Comment by AngheloAlf** [comment]
By taking a look at what you posted it seems like the endian is correct, otherwise you would get garbage instead of readable assembly.
The "invalid instructions" may be caused because of two reasons: Either those are just data instead of actual instructions or those are part of a MIPS extension. spimdisasm knows about a few extensions, you can try then with the `--instr-category` parameter.
spimdisasm only knows about a few extensions, mainly console related extensions like Sony consoles, so if this binary is not from a game then you'll be a bit out of luck

**Comment by mediotex** [comment]
Sorry, I uploaded wrong output of image1_80000300.text.s [294,2 MiB] - this large file was result of first attempt to disassemble with wrong command.  The output with correct command is 291,5 KiB and have only 69 invalid instruction marks. I reuploaded with correct file.

**Comment by AngheloAlf** [comment]
Did you tried what I mentioned earlier? It should still apply

**Comment by mediotex** [comment]
With `--instr-category` argument, where category is 'cpu'?

`$ python3 -m spimdisasm singleFileDisasm image.out out_dir --start 0x1F0 --end 0x623C --vram 0x80000300 --instr-category cpu`

**Comment by AngheloAlf** [comment]
No, `cpu` is the default, you could try the other ones

**Comment by mediotex** [comment]
`python3 -m spimdisasm singleFileDisasm image1.out out_dir2 --start 0x1F0 --end 0x623C --vram 0x80000300 --disasm-unknown --instr-category rsp`
[rsp_image1_80000300.text.s.zip](https://github.com/user-attachments/files/16055115/rsp_image1_80000300.text.s.zip)

**Comment by mediotex** [comment]
with `r3000gte,r4000allegrex,r5900`
5 marked #INVALID and 227 marked * handwritten instruction * 
What mean 'handwritten instruction'?

[instructions_image1_80000300.text.s.zip](https://github.com/user-attachments/files/16056052/instructions_image1_80000300.text.s.zip)

**Comment by AngheloAlf** [comment]
The "handwritten instruction" message is just a hint to tell the user the given instruction is usually not emitted normally by C compilers, so it may have been part of handwritten assembly instead of generated assembly from a compiler.

Since none of the MIPS extensions take care of all the invalid ones then this may be just another extension we don't know of.
Where does this binary come from? That may give you a clue to know what instruction set is being used by that binary.

**Comment by mediotex** [comment]
Its cable modem firmware, use Broadcom eCos real-time operating system for MIPS arch, have eCos side and Linux side.

**Comment by AngheloAlf** [comment]
Oh, I didn't knew MIPS was still used today, it may explain the unrecognized instructions.
spimdisasm focuses mainly on older MIPS versions (up to MIPS IV), just because it was born to reverse engineer old games like Nintendo 64 ones. If this program uses a newer MIPS version then spimdisasm won't catch many of the new instructions.
There are no plans to add support to newer MIPS versions any time soon. If you need a full proper disassembly you'll have to rely on a different tool, sorry.

**Comment by mediotex** [comment]
In order to decompile asm code to pseudo-C, do I need to have a full disassembled code without errors, or its possible to skip invalid instructions without breaking logic and relationship between functions?

**Comment by AngheloAlf** [comment]
You could get a general idea with a partial disassembly, but you may miss some important bits if you are missing instructions. It kinda depends on what you are aiming for.
Since the disassembly is almost complete you could try using some decompiler like m2c (https://github.com/matt-kempster/m2c), it gives pretty good results.

Either way, I'm closing this issue since the original problem seems to be solved.
